[build]
  command = "dotnet build" # Comando de build do .NET Core

[[plugins]]
  package = "netlify-plugin-aspnetcore" # Plugin para configurar o ambiente ASP.NET Core

  # Configuração do ambiente do ASP.NET Core
  [plugins.inputs]
    # Especificar a versão do SDK do .NET Core
    dotnet_version = "6.0"
    
    # Especificar as variáveis de ambiente do banco de dados PostgreSQL
    # Substitua os valores abaixo pelos seus próprios dados de conexão
    connection_string = "Host=pg-17e34b52-paulinho4k10-419f.aivencloud.com;Port=16602;Database=Blog;Username=avnadmin;Password=AVNS_8MJYPcc4pVaf5V_aDHj;SslMode=Require;Trust Server Certificate=true;"